#!/bin/sh
sudo dnf install wget git python3 gperftools-libs libglvnd-glx 

cd ~
trash webui.sh
trash stable-diffusion-webui
wget -q https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh
chmod +x ./webui.sh
# this should fail with a bad python version
./webui.sh
cd ./stable-diffusion/webui
trash-put ./venv
python3.10 -m venv venv
source venv/bin/activate
pip install --upgrade pip
./webui.sh --medvram
# ./webui.sh || (echo "=== script failed, creating venv ===" && sudo dnf install python3.10 && cd stable-diffusion-webui &&\
# python3.10 -m venv venv && which python && source venv/bin/activate &&\
#  pip install --upgrade pip && which python && ./webui.sh)
# echo "stable diffusion installed"
sh <(curl -sL https://raw.githubusercontent.com/12to-the12/spark/main/iprint(f"{shot_price:~P}")
