#!/bin/bash
prompt_yes_no(){
while true; do
  echo $1
  printf "(y/n)> "
  read yn

  case $yn in 
  	yes ) return 1;;
   y ) return 1;;
	  no ) return 0;;
    n ) return 0;;
    '' ) return 0;;
	  * )
      echo " $yn is an invalid response"
      sleep 0.5;;
  esac
  
  done
}

set_install_flag(){
  flag_name=$1
  if prompt_yes_no "configure $1?"; then
    eval "$flag_name=\"1\""
  else
    eval "$flag_name=\"0\""
  fi
}
