#!/bin/bash


prompt_yes_no(){
while true; do
  echo $1
  printf "(y/N)> "
  read yn

  case $yn in 
    yes )
      return 1;;
    y )
      return 0;;
    0 )
      return 0;;
    true )
      return 0;;
    no )
      return 1;;
    n )
      return 1;;
    1 )
      return 1;;
    false )
      return 1;;
    '' )
      return 1;;
    * )
      return 1
  esac
  
  done
}


set_install_flag(){
  flag_name=$1
  if prompt_yes_no "configure $1?"; then
    eval "$flag_name=\"0\""
  else
    eval "$flag_name=\"1\""
  fi
}
