#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   pprint --failure "This script must be run as root" 
   exit 1
fi
parse_args

pprint --success "Welcome to Logan's world renowned computer configuration system!"


detect_platform
set_package_manager_commands


set_setup_flags

configure_personal_system
configure_cli




pprint --success "setup finished! Enjoy your new system!"
pprint
exit 0
