#!/bin/bash
# Bash, with GNU sleep
function spinner() {
  local i=0
  local sp='/-\|'
  local n=${#sp}
  printf ' '
  while sleep 0.1; do
    printf '\b%s' "${sp:i++%n:1}"
  done
}
function spin() {
  spinner & spinpid=$!
}
function stop-spin() {
  kill $spinpid
}
